from google import genai
import json
import os
import time


def load_api_key():
    try:
        with open("api_key.txt", "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        print("ERROR: api_key.txt not found. Are you running this from the root folder?")
        return None


def critique_brand(client, brand_name, text, a3_x, a3_y, a3_x_reason, a3_y_reason):
    """Agent 4: Critiques the scores generated by Agent 3."""

    system_prompt = f"""
    You are Agent 4: The Strategic AI Critic. You are a senior brand strategist.
    Another AI (Agent 3) just scored a luxury fragrance brand on two axes.
    LLMs often score too safely (staying near 4-6). Your job is to audit Agent 3's scores and push them to the extremes (0-2 or 8-10) if the text justifies it.

    X-AXIS: DOMINANCE (0) vs. VULNERABILITY (10)
    * Dominance (0-3): Imperative verbs, superlatives, establishment markers, third-person authority.
    * Vulnerability (7-10): Somatic/fleshy words, direct address (You/I), emotional admissions.

    Y-AXIS: COLLECTIVE MYTH (0) vs. PRIVATE TRUTH (10)
    * Collective Myth (0-3): Archetypes, heritage, shared cultural touchstones, tribal gatekeeping.
    * Private Truth (7-10): Stream of consciousness, memory/nostalgia, solitude, hyper-specific details.

    TARGET BRAND: {brand_name}
    RAW TEXT: "{text}"

    AGENT 3'S INITIAL SCORES:
    X-Score: {a3_x} (Reasoning: {a3_x_reason})
    Y-Score: {a3_y} (Reasoning: {a3_y_reason})

    YOUR TASK:
    Audit these scores based strictly on the text. If Agent 3 was too safe or hallucinated, OVERRIDE the score.

    OUTPUT FORMAT: Return ONLY valid JSON. No markdown tags.
    {{
      "final_x": [Number],
      "final_y": [Number],
      "critique_log": "[One sentence explaining if you kept or changed Agent 3's scores and why.]"
    }}
    """

    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model='gemini-2.0-flash',
                contents=[system_prompt]
            )

            # Clean JSON formatting if LLM adds markdown
            raw_output = response.text.strip()
            if raw_output.startswith("```json"):
                raw_output = raw_output[7:-3].strip()
            elif raw_output.startswith("```"):
                raw_output = raw_output[3:-3].strip()

            return json.loads(raw_output)

        except Exception as e:
            error_msg = str(e)
            if "503" in error_msg or "429" in error_msg:
                print(f"  [Server busy. Retrying in 5 seconds...]")
                time.sleep(5)
            else:
                print(f"  [Failed to parse JSON for {brand_name}: {e}]")
                return None
    return None


def main():
    print("=== STARTING AGENT 4 (THE CRITIC) ===\n")

    api_key = load_api_key()
    if not api_key: return
    client = genai.Client(api_key=api_key)

    # 1. Load the original text and Agent 3's scores
    try:
        with open("data/knowledge_base/brand_data.json", "r", encoding="utf-8") as f:
            kb_data = json.load(f)
        with open("data/scores/all_brand_scores.json", "r", encoding="utf-8") as f:
            a3_scores = json.load(f)
    except FileNotFoundError as e:
        print(f"ERROR: Missing data file. {e}")
        return

    final_scores = {}

    # 2. Loop through all 10 brands and let Agent 4 critique them
    for brand, text in kb_data.items():
        if brand not in a3_scores:
            continue

        print(f"Auditing: {brand}...")
        a3_data = a3_scores[brand]

        critique = critique_brand(
            client, brand, text,
            a3_data["x_score"], a3_data["y_score"],
            a3_data["x_reasoning"], a3_data["y_reasoning"]
        )

        if critique:
            final_scores[brand] = {
                "x_score": critique["final_x"],
                "y_score": critique["final_y"],
                "x_reasoning": a3_data["x_reasoning"],  # Keep original reasoning
                "y_reasoning": a3_data["y_reasoning"],  # Keep original reasoning
                "critique": critique["critique_log"]
            }

            # Print the difference
            x_diff = critique["final_x"] - a3_data["x_score"]
            y_diff = critique["final_y"] - a3_data["y_score"]
            if x_diff != 0 or y_diff != 0:
                print(f"  > ⚠️ OVERRIDE: X adjusted by {x_diff:.1f}, Y adjusted by {y_diff:.1f}")
            else:
                print(f"  > ✅ VERIFIED: Scores maintained.")

            print(f"  > Agent 4 Log: {critique['critique_log']}")
        else:
            print(f"  > Failed to audit {brand}.")

        time.sleep(4)  # Rate limit protection

    # 3. Save the final Master JSON file
    os.makedirs("data/scores", exist_ok=True)
    master_file = "data/scores/final_brand_scores.json"
    with open(master_file, "w") as f:
        json.dump(final_scores, f, indent=4)

    print(f"\n=== CRITIQUE COMPLETE ===")
    print(f"Final audited data saved to: {master_file}")


if __name__ == "__main__":
    main()